#' Assign full taxonomy to species
#'
#' Using a kraken2 report with metaphlan formatted output, assign to the normalized table resulting from voom_snm_normalization.
#' This is also compatible with the unnormalized counts and rarefied prevalence outputs.
#' @param kraken.tax This is a kraken2 report generated by running kraken2 using the arguments --use-mpa-style and --report-zero-counts with the desired kraken2 database on a test sample. The first column of this report should be renamed "Taxonomy".
#' An example of the kraken2 output can be seen with data("krakenmet").
#' @param species.tab The table to which taxonomy whould be assigned. Samples are rows and defined in the column "sample" and species are columns.
#' @return A long formatted table with each species taxonomy reported in a column for each taxonomic level.
#' @export

assign_taxonomy <- function(kraken.tax, species.tab){
  met.good <- kraken.tax %>%
    dplyr::filter(!grepl("\n", Taxonomy))
  met.fix <- kraken.tax %>%
    dplyr::filter(grepl("\n", Taxonomy))

  fix.taxa.amalgam <- paste(met.fix$Taxonomy, collapse = "\n")
  fix.taxa.split <- stringr::str_split(pattern = "\n", fix.taxa.amalgam)[[1]]
  met.repared <- as.data.frame(cbind(Taxonomy = fix.taxa.split,
                                     V2 = 1))%>%
    tidyr::separate(Taxonomy, into = c("Taxonomy"), sep = "\t") %>%
    dplyr::mutate(V2 = as.numeric(as.character(V2)))

  taxkey <- dplyr::bind_rows(met.good, met.repared) %>%
    dplyr::filter(grepl("s__", Taxonomy)) %>%
    dplyr::mutate(specjoin = gsub(".*s__(.*)", "\\1", Taxonomy),
           specjoin = make.names(specjoin))

  exo.obj.tax <- species.tab %>%
    tidyr::gather(-sample, key = "microbe", value = "exo.ra") %>%
    dplyr::mutate(specjoin = microbe)%>%
    dplyr::left_join(taxkey) %>%
    dplyr::mutate(domain = gsub("(d__\\w+).*", "\\1", Taxonomy),
           kingdom = ifelse(grepl("k__", Taxonomy),gsub(".*(k__\\w+).*", "\\1", Taxonomy), NA),
           phylum = ifelse(grepl("p__", Taxonomy),gsub(".*(p__\\w+).*", "\\1", Taxonomy), NA),
           order = ifelse(grepl("o__", Taxonomy),gsub(".*(o__\\w+).*", "\\1", Taxonomy), NA),
           class = ifelse(grepl("c__", Taxonomy),gsub(".*(c__\\w+).*", "\\1", Taxonomy), NA),
           family = ifelse(grepl("f__", Taxonomy),gsub(".*(f__\\w+).*", "\\1", Taxonomy), NA),
           genus = ifelse(grepl("g__", Taxonomy),gsub(".*(g__\\w+).*", "\\1", Taxonomy), NA),
           species = gsub(".*(s__.*)", "\\1", Taxonomy)
    ) %>%
    dplyr::mutate(genus = ifelse(is.na(genus), paste0("g__unclassified-", species), genus),
           family = ifelse(is.na(family), paste0("f__unclassified-", gsub("g__unclassified-", "", genus)), family),
           order = ifelse(is.na(order), paste0("o__unclassified-", gsub("f__unclassified-", "", family)), order),
           class = ifelse(is.na(class), paste0("c__unclassified-", gsub("o__unclassified-", "", order)), class),
           phylum = ifelse(is.na(phylum), paste0("p__unclassified-", gsub("c__unclassified-", "", class)),phylum),
           kingdom = ifelse(is.na(kingdom), paste0("k__unclassified-", gsub("p__unclassified-", "", phylum)), kingdom),
           domain = ifelse(is.na(domain), paste0("d__unclassified-", gsub("k__unclassified-", "", kingdom)), domain)) %>%
    dplyr::select(sample, microbe, Taxonomy, domain, kingdom, phylum, class, order, family, genus, species, exo.ra)

  return(exo.obj.tax)

}
