#' Acquire TCGA clinical data
#'
#' This function interacts with Genomic Data Commons to acquire TCGA clinical data for the list of samples provided in a file manifest
#' as generated by the function generate_TCGA_manifest.
#' @param filemanifest Either the result of running generate_TCGA_manifest once or binding the results of several cancers together.
#' @return A data frame of the clinical data available from TCGA for the samples in the manifest.
#' @export

grab_TCGA_clinical <- function(filemanifest){
  grab.clinid <- GenomicDataCommons::cases(legacy = F) %>%
    GenomicDataCommons::select(c(GenomicDataCommons::default_fields("cases"), "files.file_id")) %>%
    GenomicDataCommons::filter(files.type == "aligned_reads" &
                                 project.program.name =='TCGA' &
                                 samples.sample_type == "primary tumor" &
                                 files.file_id %in% filemanifest$file_id.BAM) %>%
    GenomicDataCommons::response_all()

  for(cid in names(grab.clinid$results$files)){
    grab.clinid$results$files[[cid]] <- grab.clinid$results$files[[cid]] %>%
      dplyr::mutate(case_id = cid)
  }
  checkfilepres <- tidyverse::bind_rows(grab.clinid$results$files)

  file.case <- checkfilepres %>%
    dplyr::filter(file_id %in% filemanifest$file_id.BAM)
  choosecases <- unique(file.case$case_id)

  addtranslate <- file.case %>%
    dplyr::mutate(file_id.BAM = file_id) %>%
    dplyr::left_join(filemanifest) %>%
    dplyr::filter(grepl("count", file_name.expression)) %>%
    dplyr::select(file_id.BAM, file_id.expression, case_id, cancer, source)

  grab.clindat <- gdc_clinical(choosecases)
  clindat.form <- purrr::reduce(function(dtf1,dtf2) dplyr::full_join(dtf1,dtf2,by="case_id"),
                         grab.clindat) %>%
    dplyr::left_join(addtranslate)
  clindat.form <- clindat.form[!duplicated(clindat.form),]
  return(clindat.form)
}
